language: node_js

node_js:
  - "12.3.1"

services:
  - docker

script: echo "npm test temporarily disabled"

after_success:
  - docker build -t $DOCKER_IMAGE .

deploy:
  provider: script
  script: docker push $DOCKER_IMAGE
  on:
    branch: development